version: '3.8'

services:
    backend:
        build: ./backend
        container_name: snapspace-backend
        working_dir: /app/backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
            - "traefik.http.services.backend.loadbalancer.server.port=8000"
            - "traefik.http.routers.backend.entrypoints=web"
        volumes:
            - .:/app
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - snapspace-net

    traefik:
        image: traefik:v2.11
        container_name: snapspace-traefik
        ports:
            - "80:80"
            - "8080:8080" # Dashboard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.yml:/etc/traefik/traefik.yml
        networks:
            - snapspace-net

networks:
    snapspace-net:
        name: snapspace-net