api:
  dashboard: true
  insecure: true  # Remember to secure this in production

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

serversTransport:
  forwardingTimeouts:
    responseHeaderTimeout: 0s
    dialTimeout: 0s